-- MySQL Script generated by MySQL Workbench
-- 03/10/15 19:12:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TypesOfItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TypesOfItems` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TypesOfItems` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Items` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Items` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Price` INT NULL,
  `TypesOfItems_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Items_TypesOfItems1`
    FOREIGN KEY (`TypesOfItems_id`)
    REFERENCES `mydb`.`TypesOfItems` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Items_TypesOfItems1_idx` ON `mydb`.`Items` (`TypesOfItems_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`DeliveryMethod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DeliveryMethod` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DeliveryMethod` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Price` INT NULL,
  `Speed` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `id` INT NOT NULL,
  `Adress` VARCHAR(45) NULL,
  `CompanyName` VARCHAR(45) NULL,
  `MobileNumber` INT NULL,
  `DeliveryMethod_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Customers_DeliveryMethod`
    FOREIGN KEY (`DeliveryMethod_id`)
    REFERENCES `mydb`.`DeliveryMethod` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Customers_DeliveryMethod_idx` ON `mydb`.`Customers` (`DeliveryMethod_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `id` INT NOT NULL,
  `Items_id` INT NOT NULL,
  `Customers_id` INT NOT NULL,
  `DeliveryMethod_id` INT NOT NULL,
  `ItemsCount` INT NULL,
  `DateOrder` DATE NULL,
  `Price` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Orders_Items1`
    FOREIGN KEY (`Items_id`)
    REFERENCES `mydb`.`Items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`Customers_id`)
    REFERENCES `mydb`.`Customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_DeliveryMethod1`
    FOREIGN KEY (`DeliveryMethod_id`)
    REFERENCES `mydb`.`DeliveryMethod` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Orders_Items1_idx` ON `mydb`.`Orders` (`Items_id` ASC);

CREATE INDEX `fk_Orders_Customers1_idx` ON `mydb`.`Orders` (`Customers_id` ASC);

CREATE INDEX `fk_Orders_DeliveryMethod1_idx` ON `mydb`.`Orders` (`DeliveryMethod_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
